### ISSUE TITLE
Errors occur after "make"

### ISSUE THREAD

**Issue by zengletian1491** [peihaowang/PoissonImageEditing#1]

**Comment by zengletian1491** [comment]
This program is compiled on ubuntu16.04 LTS and the error of " ‘clock’ is not a member of ‘std’" occur.Detailed information is listed as follows:

[ 12%] Building CXX object src/CMakeFiles/POISSON_IMAGE_SHARED.dir/PoissonImage.cpp.o
In file included from /media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/PoissonImage.cpp:2:0:
/media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/StopWatch.h: In constructor ‘StopWatch::StopWatch()’:
/media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/StopWatch.h:14:31: error: ‘clock’ is not a member of ‘std’
     StopWatch() : m_startTime(std::clock()), m_lastTime(m_startTime) { return; }
                               ^
/media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/StopWatch.h:14:31: note: suggested alternative:
In file included from /usr/include/pthread.h:24:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/gthr.h:148,
                 from /usr/include/c++/5/ext/atomicity.h:35,
                 from /usr/include/c++/5/bits/ios_base.h:39,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from /media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/PoissonImage.cpp:1:
/usr/include/time.h:189:16: note:   ‘clock’
 extern clock_t clock (void) __THROW;
                ^
In file included from /media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/PoissonImage.cpp:2:0:
/media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/StopWatch.h: In member function ‘double StopWatch::escapeTime() const’:
/media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/StopWatch.h:16:49: error: ‘clock’ is not a member of ‘std’
     double escapeTime() const { return (double)(std::clock() - m_lastTime) / CLOCKS_PER_SEC; }
                                                 ^
/media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/StopWatch.h:16:49: note: suggested alternative:
In file included from /usr/include/pthread.h:24:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/gthr.h:148,
                 from /usr/include/c++/5/ext/atomicity.h:35,
                 from /usr/include/c++/5/bits/ios_base.h:39,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from /media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/PoissonImage.cpp:1:
/usr/include/time.h:189:16: note:   ‘clock’
 extern clock_t clock (void) __THROW;
                ^
In file included from /media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/PoissonImage.cpp:2:0:
/media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/StopWatch.h: In member function ‘double StopWatch::totalTime() const’:
/media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/StopWatch.h:17:48: error: ‘clock’ is not a member of ‘std’
     double totalTime() const { return (double)(std::clock() - m_startTime) / CLOCKS_PER_SEC; }
                                                ^
/media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/StopWatch.h:17:48: note: suggested alternative:
In file included from /usr/include/pthread.h:24:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/gthr.h:148,
                 from /usr/include/c++/5/ext/atomicity.h:35,
                 from /usr/include/c++/5/bits/ios_base.h:39,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from /media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/PoissonImage.cpp:1:
/usr/include/time.h:189:16: note:   ‘clock’
 extern clock_t clock (void) __THROW;
                ^
In file included from /media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/PoissonImage.cpp:2:0:
/media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/StopWatch.h: In member function ‘double StopWatch::tick(const char*)’:
/media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/StopWatch.h:23:22: error: ‘clock’ is not a member of ‘std’
         m_lastTime = std::clock();
                      ^
/media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/StopWatch.h:23:22: note: suggested alternative:
In file included from /usr/include/pthread.h:24:0,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/gthr.h:148,
                 from /usr/include/c++/5/ext/atomicity.h:35,
                 from /usr/include/c++/5/bits/ios_base.h:39,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from /media/zeng/work/texture_mapping/Poisson_Image_Editing/PoissonImageEditing-master/src/PoissonImage.cpp:1:
/usr/include/time.h:189:16: note:   ‘clock’
 extern clock_t clock (void) __THROW;
                ^
src/CMakeFiles/POISSON_IMAGE_SHARED.dir/build.make:62: recipe for target 'src/CMakeFiles/POISSON_IMAGE_SHARED.dir/PoissonImage.cpp.o' failed
make[2]: *** [src/CMakeFiles/POISSON_IMAGE_SHARED.dir/PoissonImage.cpp.o] Error 1
CMakeFiles/Makefile2:98: recipe for target 'src/CMakeFiles/POISSON_IMAGE_SHARED.dir/all' failed
make[1]: *** [src/CMakeFiles/POISSON_IMAGE_SHARED.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Could you please give me some suggestions?Thank you!

**Comment by peihaowang** [comment]
First, Thanks for your report.
I've updated some includes. Please download the latest version on master branch. The errors are supposed to be fixed.
Refer to  [std::clock - cppreference.com](https://en.cppreference.com/w/cpp/chrono/c/clock), the time-related functions were moved into `<ctime.h>` in C++.
If you still cannot compile the source code, I suggest you check the version of your compiler and make sure it supports C++11 standard.
New followups are welcome.
